apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-triton
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}-triton
spec:
  type: {{ .Values.triton.service.type }}
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  - port: 8001
    targetPort: 8001
    name: grpc
  selector:
    app: {{ .Chart.Name }}-triton